apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: infra
  namespace: argocd
spec:
  description: Project for infrastructure components
  sourceRepos:
    - https://bitnami-labs.github.io/sealed-secrets
    - https://github.com/romangulyako/argocd-apps
  destinations:
    - namespace: kube-system
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
