apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: jenkins
  namespace: argocd
spec:
  description: Project for Jenkins homework
  sourceRepos:
    - https://romangulyako.github.io/helm-jenkins
    - https://github.com/romangulyako/argocd-apps
  destinations:
    - namespace: ci-cd
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
