apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jenkins
  namespace: argocd
spec:
  project: jenkins
  source:
    repoURL: https://romangulyako.github.io/helm-jenkins
    chart: jenkins
    targetRevision: 0.1.0
  destination:
    server: https://kubernetes.default.svc
    namespace: ci-cd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
