apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-secrets
  namespace: argocd
spec:
  project: jenkins
  source:
    repoURL: https://github.com/romangulyako/argocd-apps
    targetRevision: main
    path: secrets
  destination:
    server: https://kubernetes.default.svc
    namespace: ci-cd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
